<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-07-25 07:46
=======
# Generated by Django 4.0.4 on 2022-07-24 15:16
>>>>>>> 1008316066f2a40361d0463d28f864d23d1bd6c4

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('father', models.CharField(max_length=200)),
                ('mother', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
<<<<<<< HEAD
=======
                ('slug', models.SlugField(unique=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nasel.animalmodel')),
>>>>>>> 1008316066f2a40361d0463d28f864d23d1bd6c4
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nasel.animalmodel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nasel.profilemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
