# Generated by Django 4.0.6 on 2022-07-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nasel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='profile',
        ),
    ]
