# Generated by Django 4.0.6 on 2022-07-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nasel', '0002_remove_profilemodel_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nasel.animalmodel'),
        ),
    ]
